"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestFogDBTests,
	#superclass : #PackageManifest,
	#category : 'FogDBTests'
}

{ #category : #'meta-data' }
ManifestFogDBTests class >> description [ ^ 'Test contracts deployed once for the test. It tests Mirror and remote variable access'
]
