"
Equality comparison
"
Class {
	#name : #FogVMEq,
	#superclass : #FogEVMInstruction,
	#category : 'FogEVM-ByteCode'
}

{ #category : #generated }
FogVMEq class >> byteCode [
		^'0x14'.
	
]

{ #category : #generated }
FogVMEq class >> expectedPops [
		^2.
	
]

{ #category : #generated }
FogVMEq class >> expectedPushes [
		^1.
	
]

{ #category : #generated }
FogVMEq class >> mnemonic [
		^'EQ'.
	
]
