SystemOrganization addCategory: #FogEQL!
SystemOrganization addCategory: 'FogEQL-Buffers'!
SystemOrganization addCategory: 'FogEQL-EQL-Interpreter'!
SystemOrganization addCategory: 'FogEQL-Indexes'!
SystemOrganization addCategory: 'FogEQL-SemanticAST'!
SystemOrganization addCategory: 'FogEQL-SemanticAST-BinaryOperators'!
SystemOrganization addCategory: 'FogEQL-SemanticAST-UnaryOperators'!
SystemOrganization addCategory: 'FogEQL-Streams'!
