SystemOrganization addCategory: #FogCommunication!
SystemOrganization addCategory: 'FogCommunication-API'!
SystemOrganization addCategory: 'FogCommunication-Connection'!
SystemOrganization addCategory: 'FogCommunication-Transfer'!
SystemOrganization addCategory: 'FogCommunication-Transfer-Call'!
SystemOrganization addCategory: 'FogCommunication-Transfer-Filters'!
SystemOrganization addCategory: 'FogCommunication-Util'!
